# example of a compose file
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.05.1
    # [...] all your pihole parameters [...]

  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:v0.11.0
    # platform: linux/arm64 # if needed, eg for linux/arm/v8
    container_name: nebula-sync
    environment:
      TZ: Europe/Paris
      PRIMARY: http://192.168.1.20:8086|myPrimaryPassword
      REPLICAS: http://192.168.1.80:8087|myReplicaPassword
      RUN_GRAVITY: true
      CRON: 0 * * * *
      FULL_SYNC: false
      SYNC_CONFIG_DNS: true
      SYNC_CONFIG_DHCP: true
      SYNC_CONFIG_NTP: true
      SYNC_CONFIG_RESOLVER: true
      SYNC_CONFIG_DATABASE: true
      SYNC_CONFIG_MISC: true
      SYNC_CONFIG_DEBUG: true
      SYNC_GRAVITY_DHCP_LEASES: true
      SYNC_GRAVITY_GROUP: true
      SYNC_GRAVITY_AD_LIST: true
      SYNC_GRAVITY_AD_LIST_BY_GROUP: true
      SYNC_GRAVITY_DOMAIN_LIST: true
      SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: true
      SYNC_GRAVITY_CLIENT: true
      SYNC_GRAVITY_CLIENT_BY_GROUP: true
      SYNC_CONFIG_DHCP_EXCLUDE: active   # dhcp server activation should NOT be replicated !
      SYNC_CONFIG_DNS_EXCLUDE: interface # add any other parameters you don't want to replicate
    depends_on:
      pihole:
        condition: service_healthy

  monitor:
    image: ghcr.io/jerome-labidurie/pihole-dhcp-ha:latest
    container_name: monitor
    environment:
      TZ: Europe/Paris
      MPH_PRIMARY: http://192.168.1.20:8086
      MPH_SECONDARY: http://192.168.1.80:8087|myReplicaPassword
      # MPH_MONITOR_DELAY: 60
      # MPH_VERBOSE: 1
      # MPH_SECONDARY_MAC: 0a:df:de:ad:be:ef
    depends_on:
      pihole:
        condition: service_healthy
